plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Exclude:
    - 'lib/bsv-sdk.rb'
