# frozen_string_literal: true

require 'spec_helper'
require 'bsv-wallet'

# Cross-SDK integration tests for BSV::Auth certificate infrastructure.
#
# Verifies:
# - End-to-end lifecycle (issue → reveal → decrypt → verify)
# - Binary format compatibility with the TS SDK reference implementation
# - Cross-verification between Certificate#to_binary and CertificateSignature.serialise_preimage
# - TS fromObject test vector attribute parsing
# - Multi-field selective revelation
# - Self-signed certificates
#
# Deterministic keys (matching TS SDK fixtures): PrivateKey(21), PrivateKey(22), PrivateKey(23).
# The binary test vector below was generated by running Certificate#to_binary on known inputs
# and confirmed byte-identical to the TS SDK toBinary output for the same data.

# rubocop:disable RSpec/DescribeClass

# Static binary test vector — generated from Certificate#to_binary(include_signature: false)
# using PrivateKey(21) as subject, PrivateKey(22) as certifier, type=0x01*32,
# serial=0x02*32, outpoint=deadbeef…00.1, fields={email, name} (sorted).
# Verified byte-identical to TS SDK toBinary(false) output for the same inputs.
#
# Byte layout (199 bytes):
#   [0..31]   type (32 bytes, all 0x01)
#   [32..63]  serial_number (32 bytes, all 0x02)
#   [64..96]  subject pubkey (33 bytes, compressed)
#   [97..129] certifier pubkey (33 bytes, compressed)
#   [130..161] revocation txid (32 bytes, deadbeef…)
#   [162]     output index varint (0x01 = 1)
#   [163]     field count varint (0x02 = 2)
#   [164..]   field 0: "email" + "alice@example.com" (sorted first)
#   [...]     field 1: "name"  + "Alice"
CERT_BINARY_NO_SIG_HEX =
  '0101010101010101010101010101010101010101010101010101010101010101' \
  '0202020202020202020202020202020202020202020202020202020202020202' \
  '02352bbf4a4cdd12564f93fa332ce333301d9ad40271f8107181340aef25be59d5' \
  '03421f5fc9a21065445c96fdb91c0c1e2f2431741c72713b4b99ddcb316f31e9fc' \
  'deadbeefdeadbeefdeadbeefdeadbeef00000000000000000000000000000000' \
  '010205656d61696c11616c696365406578616d706c652e636f6d046e616d6505416c696365'

# TS SDK fromObject test vector — type decodes to 21 bytes (not 32).
# Designed to test attribute parsing only, not binary round-trips.
CERT_TS_VECTOR_MULTI_FIELD = {
  'type' => 'Q29tbW9uU291cmNlIGlkZW50aXR5',
  'serial_number' => 'UegX3uufsqHsbEKeBSxUd9AziLSyru86TnwfhPoZJYE=',
  'subject' => '028e2e075e1e57ba4c62c90125468109f9b4e2a7741da3dd76ccd0c73b2a8a37ad',
  'certifier' => '03c644fe2fd97673a5d86555a58587e7936390be6582ece262bc387014bcff6fe4',
  'revocation_outpoint' => '0245242bd144a85053b4c1e4a0ed5467c79a4d172680ca77a970ebabd682d564.0',
  'signature' => '304402202c86ef816c469fe657289ddea12d2c444f006ef5ab5851f00107c7724eb67ea6' \
                 '02202786244c077567c8f3ec5da78bd61ce0c35bf1eeac0488e026c03b21c403b0fd',
  'fields' => {
    'displayName' => 'eqsSpUgTKk891y1EkyCPPg+C4YoVZJvB0EQ4iore7VofkM5TB9Ctj7x2PgBaWI0A9tfATDO9',
    'email' => 'n6HVUvyHkIDMvB4ERxVGxmX6lgRBM+e7kbbC5DiRCKe5a60BJeXr05g4POq6OHYO9Wl/b1Xxe+JKsejl',
    'phoneNumber' => '5yWyN9kOGaZs5G6yvXUWnWj4rm7kDAug4YIsn4BQLKGYRzDx8s1dytb43ega6BnSp0gUTnskcjiM8ekqul2a'
  }
}.freeze

RSpec.describe 'BSV::Auth certificate integration' do # rubocop:disable RSpec/DescribeClass
  # Deterministic keys matching TS SDK test fixtures
  let(:subject_key)   { BSV::Primitives::PrivateKey.new(OpenSSL::BN.new(21)) }
  let(:certifier_key) { BSV::Primitives::PrivateKey.new(OpenSSL::BN.new(22)) }
  let(:verifier_key)  { BSV::Primitives::PrivateKey.new(OpenSSL::BN.new(23)) }

  let(:subject_wallet)   { BSV::Wallet::Client.new(subject_key, storage: BSV::Wallet::Store::Memory.new, allow_memory_store: true) }
  let(:certifier_wallet) { BSV::Wallet::Client.new(certifier_key, storage: BSV::Wallet::Store::Memory.new, allow_memory_store: true) }
  let(:verifier_wallet)  { BSV::Wallet::Client.new(verifier_key, storage: BSV::Wallet::Store::Memory.new, allow_memory_store: true) }

  let(:subject_hex)   { subject_key.public_key.to_hex }
  let(:certifier_hex) { certifier_key.public_key.to_hex }
  let(:verifier_hex)  { verifier_key.public_key.to_hex }

  # Deterministic cert data — same values used to generate CERT_BINARY_NO_SIG_HEX
  let(:cert_type)   { Base64.strict_encode64("\x01" * 32) }
  let(:serial)      { Base64.strict_encode64("\x02" * 32) }
  let(:outpoint)    { 'deadbeefdeadbeefdeadbeefdeadbeef00000000000000000000000000000000.1' }
  let(:plain_fields) { { 'email' => 'alice@example.com', 'name' => 'Alice' } }

  # ===========================================================================
  # 1. Autoload resolution
  # ===========================================================================

  describe 'autoload resolution' do
    it 'resolves BSV::Auth::Certificate without errors' do
      expect(defined?(BSV::Auth::Certificate)).to eq('constant')
    end

    it 'resolves BSV::Auth::VerifiableCertificate without errors' do
      expect(defined?(BSV::Auth::VerifiableCertificate)).to eq('constant')
    end

    it 'resolves BSV::Auth::MasterCertificate without errors' do
      expect(defined?(BSV::Auth::MasterCertificate)).to eq('constant')
    end
  end

  # ===========================================================================
  # 2. Binary format cross-SDK compatibility
  # ===========================================================================

  describe 'Binary format cross-SDK compatibility' do
    # The test vector was produced by running Certificate#to_binary(include_signature: false)
    # with deterministic inputs and confirming the hex matches the TS SDK toBinary(false) output.
    it 'to_binary without signature matches the pre-generated TS SDK test vector' do
      cert = BSV::Auth::Certificate.new(
        type: cert_type,
        serial_number: serial,
        subject: subject_hex,
        certifier: certifier_hex,
        revocation_outpoint: outpoint,
        fields: plain_fields
      )

      expected_hex = CERT_BINARY_NO_SIG_HEX.tr(' ', '')
      expect(cert.to_binary(include_signature: false).unpack1('H*')).to eq(expected_hex)
    end

    it 'from_binary on the pre-generated vector deserialises to the correct field values' do
      bin = [CERT_BINARY_NO_SIG_HEX.tr(' ', '')].pack('H*')
      cert = BSV::Auth::Certificate.from_binary(bin)

      expect(cert.type).to eq(cert_type)
      expect(cert.serial_number).to eq(serial)
      expect(cert.subject).to eq(subject_hex)
      expect(cert.certifier).to eq(certifier_hex)
      expect(cert.revocation_outpoint).to eq(outpoint)
      expect(cert.fields).to eq(plain_fields)
      expect(cert.signature).to be_nil
    end

    it 'round-trips: from_binary(to_binary(no_sig)).to_binary matches original' do
      cert = BSV::Auth::Certificate.new(
        type: cert_type,
        serial_number: serial,
        subject: subject_hex,
        certifier: certifier_hex,
        revocation_outpoint: outpoint,
        fields: plain_fields
      )

      bin_original = cert.to_binary(include_signature: false)
      restored     = BSV::Auth::Certificate.from_binary(bin_original)

      expect(restored.to_binary(include_signature: false)).to eq(bin_original)
    end

    it 'binary layout has the documented field order: type(32)+serial(32)+subject(33)+certifier(33)+outpoint(33)+fields' do
      cert = BSV::Auth::Certificate.new(
        type: cert_type,
        serial_number: serial,
        subject: subject_hex,
        certifier: certifier_hex,
        revocation_outpoint: outpoint,
        fields: {}
      )

      bin = cert.to_binary(include_signature: false)
      pos = 0

      type_bytes = bin.byteslice(pos, 32)
      expect(Base64.strict_encode64(type_bytes)).to eq(cert_type)
      pos += 32

      serial_bytes = bin.byteslice(pos, 32)
      expect(Base64.strict_encode64(serial_bytes)).to eq(serial)
      pos += 32

      subject_bytes = bin.byteslice(pos, 33)
      expect(subject_bytes.unpack1('H*')).to eq(subject_hex)
      pos += 33

      certifier_bytes = bin.byteslice(pos, 33)
      expect(certifier_bytes.unpack1('H*')).to eq(certifier_hex)
      pos += 33

      # Outpoint: 32-byte txid + varint output index
      txid_bytes = bin.byteslice(pos, 32)
      expect(txid_bytes.unpack1('H*')).to eq('deadbeefdeadbeefdeadbeefdeadbeef00000000000000000000000000000000')
      pos += 32

      output_index, vi_len = BSV::Transaction::VarInt.decode(bin, pos)
      expect(output_index).to eq(1)
      pos += vi_len

      # Field count = 0
      field_count, = BSV::Transaction::VarInt.decode(bin, pos)
      expect(field_count).to eq(0)
    end
  end

  # ===========================================================================
  # 3. Cross-verification with CertificateSignature.serialise_preimage
  # ===========================================================================

  describe 'Cross-verification with BSV::Wallet::CertificateSignature' do
    let(:cert_hash) do
      {
        type: cert_type,
        serial_number: serial,
        subject: subject_hex,
        certifier: certifier_hex,
        revocation_outpoint: outpoint,
        fields: plain_fields
      }
    end

    it 'Certificate#to_binary(include_signature: false) is byte-identical to CertificateSignature.serialise_preimage' do
      cert = BSV::Auth::Certificate.new(
        type: cert_type,
        serial_number: serial,
        subject: subject_hex,
        certifier: certifier_hex,
        revocation_outpoint: outpoint,
        fields: plain_fields
      )

      preimage = BSV::Wallet::CertificateSignature.serialise_preimage(cert_hash)
      expect(cert.to_binary(include_signature: false)).to eq(preimage)
    end

    it 'fields are sorted lexicographically in both implementations' do
      # Use fields that would differ if not sorted correctly
      fields_unsorted = { 'zebra' => 'z_value', 'apple' => 'a_value', 'mango' => 'm_value' }
      cert = BSV::Auth::Certificate.new(
        type: cert_type,
        serial_number: serial,
        subject: subject_hex,
        certifier: certifier_hex,
        revocation_outpoint: outpoint,
        fields: fields_unsorted
      )

      cert_hash_unsorted = cert_hash.merge(fields: fields_unsorted)
      preimage = BSV::Wallet::CertificateSignature.serialise_preimage(cert_hash_unsorted)

      expect(cert.to_binary(include_signature: false)).to eq(preimage)
    end
  end

  # ===========================================================================
  # 4. TS fromObject test vector — attribute parsing
  # ===========================================================================

  describe 'TS SDK fromObject test vector' do
    let(:ts_cert) { BSV::Auth::Certificate.from_hash(CERT_TS_VECTOR_MULTI_FIELD) }

    it 'parses all attributes from the TS vector correctly' do
      expect(ts_cert.type).to eq(CERT_TS_VECTOR_MULTI_FIELD['type'])
      expect(ts_cert.serial_number).to eq(CERT_TS_VECTOR_MULTI_FIELD['serial_number'])
      expect(ts_cert.subject).to eq(CERT_TS_VECTOR_MULTI_FIELD['subject'])
      expect(ts_cert.certifier).to eq(CERT_TS_VECTOR_MULTI_FIELD['certifier'])
      expect(ts_cert.revocation_outpoint).to eq(CERT_TS_VECTOR_MULTI_FIELD['revocation_outpoint'])
      expect(ts_cert.signature).to eq(CERT_TS_VECTOR_MULTI_FIELD['signature'])
      expect(ts_cert.fields).to eq(CERT_TS_VECTOR_MULTI_FIELD['fields'])
    end

    it 'to_h/from_hash round-trips the TS vector without data loss' do
      restored = BSV::Auth::Certificate.from_hash(ts_cert.to_h)
      expect(restored.to_h).to eq(ts_cert.to_h)
    end

    it 'also accepts camelCase serialNumber / revocationOutpoint keys' do
      camel_hash = {
        'type' => CERT_TS_VECTOR_MULTI_FIELD['type'],
        'serialNumber' => CERT_TS_VECTOR_MULTI_FIELD['serial_number'],
        'subject' => CERT_TS_VECTOR_MULTI_FIELD['subject'],
        'certifier' => CERT_TS_VECTOR_MULTI_FIELD['certifier'],
        'revocationOutpoint' => CERT_TS_VECTOR_MULTI_FIELD['revocation_outpoint'],
        'fields' => CERT_TS_VECTOR_MULTI_FIELD['fields']
      }

      cert = BSV::Auth::Certificate.from_hash(camel_hash)
      expect(cert.serial_number).to eq(CERT_TS_VECTOR_MULTI_FIELD['serial_number'])
      expect(cert.revocation_outpoint).to eq(CERT_TS_VECTOR_MULTI_FIELD['revocation_outpoint'])
    end
  end

  # ===========================================================================
  # 5. End-to-end lifecycle: issue → sign → keyring → decrypt → verify
  # ===========================================================================

  describe 'End-to-end lifecycle' do
    let(:cert_type_32) { Base64.strict_encode64("\x03" * 32) }

    it 'full lifecycle: issue MasterCertificate, subject decrypts, create verifier keyring, VerifiableCertificate decrypts, verify signature' do
      # Step 1: certifier issues a signed MasterCertificate for the subject
      master = BSV::Auth::MasterCertificate.issue_certificate_for_subject(
        certifier_wallet,
        subject_hex,
        plain_fields,
        cert_type_32
      )

      expect(master).to be_a(BSV::Auth::MasterCertificate)
      expect(master.signature).to be_a(String)
      expect(master.signature).not_to be_empty
      expect(master.verify).to be(true)

      # Step 2: subject decrypts their own fields via the master keyring
      decrypted_by_subject = BSV::Auth::MasterCertificate.decrypt_fields(
        subject_wallet,
        master.master_keyring,
        master.fields,
        certifier_hex
      )

      expect(decrypted_by_subject).to eq(plain_fields)

      # Step 3: subject creates a verifier-specific keyring
      verifier_keyring = BSV::Auth::MasterCertificate.create_keyring_for_verifier(
        subject_wallet,
        certifier: certifier_hex,
        verifier: verifier_hex,
        fields: master.fields,
        fields_to_reveal: plain_fields.keys,
        master_keyring: master.master_keyring,
        serial_number: master.serial_number
      )

      expect(verifier_keyring.keys).to match_array(plain_fields.keys)

      # Step 4: verifier constructs a VerifiableCertificate and decrypts
      verifiable = BSV::Auth::VerifiableCertificate.from_certificate(master, verifier_keyring)
      decrypted  = verifiable.decrypt_fields(verifier_wallet)

      expect(decrypted).to eq(plain_fields)
      expect(verifiable.decrypted_fields).to eq(plain_fields)

      # Step 5: the certificate signature is still valid throughout
      expect(verifiable.verify).to be(true)
    end

    it 'binary round-trip preserves all data across the full lifecycle' do
      master = BSV::Auth::MasterCertificate.issue_certificate_for_subject(
        certifier_wallet,
        subject_hex,
        plain_fields,
        cert_type_32
      )

      # Serialise to binary and reconstruct as a base Certificate
      bin       = master.to_binary(include_signature: true)
      restored  = BSV::Auth::Certificate.from_binary(bin)

      expect(restored.type).to eq(master.type)
      expect(restored.serial_number).to eq(master.serial_number)
      expect(restored.subject).to eq(master.subject)
      expect(restored.certifier).to eq(master.certifier)
      expect(restored.revocation_outpoint).to eq(master.revocation_outpoint)
      expect(restored.fields).to eq(master.fields)
      expect(restored.signature).to eq(master.signature)

      # Signature remains valid after round-trip
      expect(restored.verify).to be(true)
    end
  end

  # ===========================================================================
  # 6. Multi-field selective revelation
  # ===========================================================================

  describe 'Multi-field selective revelation' do
    let(:multi_fields) do
      { 'name' => 'Alice', 'email' => 'alice@example.com', 'role' => 'admin' }
    end

    let(:master_multi) do
      BSV::Auth::MasterCertificate.issue_certificate_for_subject(
        certifier_wallet,
        subject_hex,
        multi_fields,
        cert_type
      )
    end

    it 'verifier can decrypt only the 2 revealed fields when certificate has 3 fields' do
      keyring = BSV::Auth::MasterCertificate.create_keyring_for_verifier(
        subject_wallet,
        certifier: certifier_hex,
        verifier: verifier_hex,
        fields: master_multi.fields,
        fields_to_reveal: %w[name email],
        master_keyring: master_multi.master_keyring,
        serial_number: master_multi.serial_number
      )

      cert = BSV::Auth::VerifiableCertificate.from_certificate(master_multi, keyring)
      decrypted = cert.decrypt_fields(verifier_wallet)

      expect(decrypted.keys).to match_array(%w[name email])
      expect(decrypted['name']).to eq('Alice')
      expect(decrypted['email']).to eq('alice@example.com')
    end

    it 'unrevealed fields remain encrypted and cannot be decrypted via the partial keyring' do
      partial_keyring = BSV::Auth::MasterCertificate.create_keyring_for_verifier(
        subject_wallet,
        certifier: certifier_hex,
        verifier: verifier_hex,
        fields: master_multi.fields,
        fields_to_reveal: ['name'],
        master_keyring: master_multi.master_keyring,
        serial_number: master_multi.serial_number
      )

      cert = BSV::Auth::VerifiableCertificate.from_certificate(master_multi, partial_keyring)
      decrypted = cert.decrypt_fields(verifier_wallet)

      expect(decrypted).not_to have_key('role')
      expect(decrypted).not_to have_key('email')
      # The field values for unrevealed fields are still present but encrypted
      expect(master_multi.fields).to have_key('role')
    end
  end

  # ===========================================================================
  # 7. Self-signed certificate
  # ===========================================================================

  describe 'Self-signed certificate' do
    it 'subject and certifier are the same wallet — full lifecycle works' do
      # Certifier issues certificate with themselves as subject
      self_cert = BSV::Auth::MasterCertificate.issue_certificate_for_subject(
        certifier_wallet,
        certifier_hex,
        plain_fields,
        cert_type
      )

      expect(self_cert.subject).to eq(certifier_hex)
      expect(self_cert.certifier).to eq(certifier_key.public_key.to_hex)
      expect(self_cert.verify).to be(true)

      # Certifier decrypts their own fields
      decrypted = BSV::Auth::MasterCertificate.decrypt_fields(
        certifier_wallet,
        self_cert.master_keyring,
        self_cert.fields,
        'self'
      )

      expect(decrypted).to eq(plain_fields)
    end

    it "'self' subject resolves to certifier identity key" do
      self_cert = BSV::Auth::MasterCertificate.issue_certificate_for_subject(
        certifier_wallet,
        'self',
        plain_fields,
        cert_type
      )

      certifier_identity = certifier_wallet.get_public_key({ identity_key: true })[:public_key]
      expect(self_cert.subject).to eq(certifier_identity)
    end

    it 'self-signed certificate sign → deserialise → verify round-trip' do
      self_cert = BSV::Auth::MasterCertificate.issue_certificate_for_subject(
        certifier_wallet,
        certifier_hex,
        plain_fields,
        cert_type
      )

      bin       = self_cert.to_binary(include_signature: true)
      restored  = BSV::Auth::Certificate.from_binary(bin)

      expect(restored.verify).to be(true)
    end
  end
end
# rubocop:enable RSpec/DescribeClass
